image: ubuntu

environment:
  github_auth_token:
    secure: 5TD7b0UBRJmIFj6X1CWJnDnnl/tkpoWnpDdy3CnPwpR+Indp/aSXdp14xACOGm45

before_build:
  - sh: docker build --tag private/rabbitmq-public-umbrella --file ./Dockerfile ./context/

build_script:
  - sh: docker run --rm --mount "type=bind,source=/home/appveyor/projects/amqp-filter-exchange,target=/var/opt/amqp-filter-exchange" private/rabbitmq-public-umbrella

after_build:
  - sh: 7z a amqp_filter_exchange.zip /home/appveyor/projects/amqp-filter-exchange/plugins/amqp_filter_exchange*.ez
  - sh: 7z a amqp_filter_exchange.zip /home/appveyor/projects/amqp-filter-exchange/plugins/amqp_filter*.ez
  - sh: 7z a amqp_filter_exchange.zip /home/appveyor/projects/amqp-filter-exchange/plugins/action_reader*.ez

artifacts:
  - path: amqp_filter_exchange.zip
    name: plugin
    type: file

deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: $Env:github_auth_token
  artifact: /amqp_filter_exchange\.zip/
  draft: false
  prerelease: false
  on:
    branch: master                 
    APPVEYOR_REPO_TAG: true        
