image: ubuntu

environment:
  github_auth_token:
    secure: OCMyGTAT++mBzpAtCFokNrb6HW/uppvgWXcW4w0vIxFEpFBdS37eS5zle+4UQ5Je

before_build:
  - sh: docker build --tag private/rabbitmq-public-umbrella --file ./Dockerfile ./context/

build_script:
  - sh: docker run --rm --mount "type=bind,source=/home/appveyor/projects/amqp-filter-exchange,target=/var/opt/amqp-filter-exchange" private/rabbitmq-public-umbrella

artifacts:
  - path: amqp_filter_exchange-1.0.ez

deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: $Env:github_auth_token
  draft: false
  prerelease: false
  on:
    branch: master                 
    APPVEYOR_REPO_TAG: true        
