image: ubuntu

before_build:
  - sh: docker build --tag private/rabbitmq-public-umbrella --file ./Dockerfile ./context/

build_script:
  - sh: docker run --rm --mount "type=bind,source=/home/appveyor/projects/amqp-filter-exchange,target=/var/opt/amqp-filter-exchange" private/rabbitmq-public-umbrella

artifacts:
  - path: plugins/amqp_filter_exchange*.ez
    name: plugin
    type: file

deploy:
  release: amqp-filter-exchange-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 919fcb6e82d171017378d09392fbf58adfb665ce 
  artifact: /.*\.ez
  draft: false
  prerelease: false
  on:
    branch: master                 
    APPVEYOR_REPO_TAG: true        
